### ISSUE TITLE
Build fails with linker error, due to bad positioning of LD_FLAGS

### ISSUE THREAD

**Issue by matthiasaechtner** [xaizek/zograscope#1]
Hi,
on my machine `make` did not run through. I had to move `$(LD_FLAGS)` to the end of the line on line 119 in file `Makefile`, then it works.
Cheers,
Matthias

**Comment by xaizek** [comment]
Hi,

Thanks for pointing that out. Not sure why it works for me, but `-l` indeed should follow object files.
