### ISSUE TITLE
Makefile parsing fails

### ISSUE THREAD

**Issue by tritao** [xaizek/zograscope#3]
Just tried to highlight a Makefile with `zs-hi` and get a parsing error.

```
➜  zograscope git:(master) ./zs-hi --lang make ../nuttx/arch/arm/src/Makefile
../nuttx/arch/arm/src/Makefile:168:43: parse error: syntax error, unexpected ':', expecting NL or LEADING_TAB
Failed to parse: ../nuttx/arch/arm/src/Makefile
```

Makefile: https://gist.github.com/tritao/50b838d940ff4a5c753361e9c513e03f

**Comment by xaizek** [comment]
Thanks. Static pattern rules and colon in the first argument of a function call should be parsed fine now.

**Comment by tritao** [comment]
Thanks so much for the fixes.
