### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by amejiarosario** [xaizek/zograscope#8]
Hi,
This project looks great and I'd like to try it out. However, I'm new to C++ and having some difficulties installing the program.

Could you please provide instructions how to get the dependencies installed (e.g., Boost)?
 
![image](https://user-images.githubusercontent.com/418605/102354289-5c2cd700-3f78-11eb-96d0-2ba092b36aac.png)

**Comment by xaizek** [comment]
Hello,

it depends on the distribution you're using. List of additional packages for Ubuntu is listed in [.travis.yml](https://github.com/xaizek/zograscope/blob/master/.travis.yml):
 - libboost-filesystem-dev
 - libboost-iostreams-dev
 - libboost-program-options-dev
 - libboost-system-dev
 - libarchive13

`libarchive13` is a dependency of SrcML, for which you can download a binary from [their site](https://www.srcml.org/).

You can avoid building by using AppImage from [releases page](https://github.com/xaizek/zograscope/releases), which I have just updated to include latest changes. You just download and make it executable, should work in most environments.

**Comment by amejiarosario** [comment]
Thanks for the pointer. Looking at the travis.yml was useful. After some trial and error, I found that `bison` and `flex` were also needed.

```sh
sudo apt install -y libboost-filesystem-dev libboost-iostreams-dev libboost-program-options-dev libboost-system-dev libarchive13
sudo apt install -y bison flex
```

Do you mind if I create a PR expanding on installation instructions to help other users?

**Comment by xaizek** [comment]
> Do you mind if I create a PR expanding on installation instructions to help other users?

Of course I don't mind.
